plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'maven-publish'
}

tasks.register("completeJar", Jar) {
    archiveClassifier = "multiloader"
    archiveBaseName = "stator"
    archiveVersion = project.version.toString()
    destinationDirectory = layout.buildDirectory.dir("libs")

    dependsOn(":common:classes", ":fabric:classes", ":neoforge:classes")

    from(project(":common").sourceSets.main.output)
    from(project(":fabric").sourceSets.main.output)
    from(project(":neoforge").sourceSets.main.output)

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version

            artifact(tasks.named('completeJar')) {
                classifier = 'multiloader'
                extension = 'jar'
            }
        }
    }
}