#Required Properties
org.gradle.jvmargs=-Xmx4G
neogradle.subsystems.conventions.sourcesets.automatic-inclusion=false
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
neogradle.subsystems.conventions.configurations.enabled=false
neogradle.subsystems.conventions.jarjar.create-main-jarjar=false

group = net.ramixin

#Metadata
mod_id = stator
version = 1.0.0
mod_name = Stator
description = A framework for multi-loader minecraft APIs
authors = Ramixin
license = MIT

minecraft_support = [26.1,)